version: '2'
services:
  wordpress:
    environment:
      - WORDPRESS_DATABASE_USER=${bn_wordpress}
      - WORDPRESS_DATABASE_NAME=${bitnami_wordpress}
      - VIRTUAL_HOST=booking.pojoni.at
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=booking.pojoni.at
      - LETSENCRYPT_EMAIL=letsencrypt@pojoni.at
  maridb:
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes

