version: '2'
services:
  wordpress:
    environment:
      - WORDPRESS_DATABASE_USER=${DATABASE_USER}
      - WORDPRESS_DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - WORDPRESS_DATABASE_NAME=${DATABASE_NAME}
      - VIRTUAL_HOST=${DOMAIN_NAME}
      - VIRTUAL_NETWORK=${DOCKER_NETWORK}
      - LETSENCRYPT_HOST=${DOMAIN_NAME}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
  mariadb:
    environment:
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_DATABASE=${DATABASE_NAME}
      - MARIADB_PORT_NUMBER="${DATABASE_PORT_NUMBER}"