version: '2'
services:
  wordpress:
    environment:
      - WORDPRESS_DATABASE_USER=${DATABASE_USER}
      - WORDPRESS_DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - WORDPRESS_DATABASE_NAME=${DATABASE_NAME}
      - VIRTUAL_HOST=${DOMAIN_NAME}
      - VIRTUAL_NETWORK=${DOCKER_NETWORK}
      - LETSENCRYPT_HOST=${DOMAIN_NAME}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
  mariadb:
    environment:
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_DATABASE=${DATABASE_NAME}
      - MARIADB_PORT_NUMBER="${DATABASE_PORT_NUMBER}"
  git-sync:
    image: openweb/git-sync:latest
    environment:
      GIT_SYNC_REPO: "git@github.com:Yoast/wordpress-seo.git"
      GIT_SYNC_DEST: "/git"
      GIT_SYNC_BRANCH: "master"
      GIT_SYNC_REV: "FETCH_HEAD"
      GIT_SYNC_WAIT: "${GIT_SYNC_SECONDS}"
    volumes:
      - ./plugins/wordpress-seo:/git:z
      # include line below in case you need your local ssh keys
      # - ~/.ssh:/root/.ssh:ro
    restart: always