version: '2'
services:
  wordpress:
    environment:
      - WORDPRESS_DATABASE_USER=${bn_wordpress}
      - WORDPRESS_DATABASE_NAME=${bitnami_wordpress}
      - VIRTUAL_HOST=booking.pojoni.at
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=booking.pojoni.at
      - LETSENCRYPT_EMAIL=letsencrypt@pojoni.at
  maridb:
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  git-sync:
    image: openweb/git-sync:latest
    environment:
      GIT_SYNC_REPO: "git@github.com:Yoast/wordpress-seo.git"
      GIT_SYNC_DEST: "/git"
      GIT_SYNC_BRANCH: "master"
      GIT_SYNC_REV: "FETCH_HEAD"
      GIT_SYNC_WAIT: "${GIT_SYNC_SECONDS}"
    volumes:
      - ./plugins/wordpress-seo:/git:z
      # include line below in case you need your local ssh keys
      # - ~/.ssh:/root/.ssh:ro
    restart: always
